Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.box_check_update = false
  config.vm.network "private_network", type: "dhcp"
  config.vm.hostname = "ubuntu20-1"
  config.vm.define "ubuntu20-1"
  config.vm.synced_folder "/Users/id/wrk/netauto/", "/netauto"
  config.vm.provision "shell", path: "config.sh"
end  

