Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-8"
  config.vm.box_check_update = false
  config.vm.hostname = "centos8-1"
  config.vm.define "centos8-1"
  config.vm.synced_folder "/Users/id/wrk/netauto/", "/netauto"
  config.vm.provision "shell", path: "config.sh"
end
